### ISSUE TITLE
Move to core libraries

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-arraybuffer-types#1]
@garyb, @jacereda would like to move this to core, and it looks good to me. It seems to fall into the same category as `purescript-dom`. Is there anything that you think is missing? Or does it overlap with any existing library?

**Comment by garyb** [comment]
Thought I'd already replied to this, sorry!

Looks good to me as-is, and it certainly doesn't overlap with anything in core or contrib at least. Node's `Buffer` is its own separate thing.

:+1:

As an aside, is this going in "actual core" or contrib? Have we even worked out what we want to do about that yet? `purescript-dom` is in `contrib` currently.

**Comment by jacereda** [comment]
I guess it doesn't matter that much as long as we have a 'blessed' view of what those types are. If the plan is to put purescript-dom in core at some point, then maybe putting this one in core might be better.

**Comment by garyb** [comment]
This is probably "more-core" than `purescript-dom` actually, as that is environment-dependent, whereas this is not (aside from being not-ancient-JS-engine-dependent!).

**Comment by garyb** [comment]
Thanks!
