### ISSUE TITLE
Introduce Purescript Mapping Functions Between Buffer Types

### ISSUE THREAD

**Issue by AlexaDeWit** [purescript-contrib/purescript-arraybuffer-types#10]
Consider this a sort of RFC... But what are your thoughts on adding to this library functions which translate between various buffer types as well as enable their construction?

**Comment by AlexaDeWit** [comment]
An example of me doing a bit of experimental work on this can be viewed here:

https://github.com/purescript-contrib/purescript-arraybuffer-types/compare/master...AlexaDeWit:master

Another thought I am considering is to insteat use purescript-arraybuffer-types as a dependency which I re-export in another more "heavy" purescript-arraybuffer library that provides the other tooling that's likely to be needed by individuals using arraybuffers.

**Comment by jacereda** [comment]
I'd keep this one as is and build on top of it. The original intent was to have an agreed type so that different libraries could share array buffers. This could belong to something like https://github.com/jacereda/purescript-arraybuffer or a library on its own.

**Comment by AlexaDeWit** [comment]
Ah, thanks, I had gone looking and not found an appropriate library. I just wanted to sort of see what the feeling was. Makes sense to me!

**Comment by AlexaDeWit** [comment]
Functionality has been merged into purescript-arraybuffer.
