### ISSUE TITLE
Instances for `Eq`

### ISSUE THREAD

**Issue by xcthulhu** [purescript-contrib/purescript-arraybuffer-types#11]
I have a simple utility function for comparing when two typed array primitives are equal:

```js
exports.arrayEquals = function(dv1) {
  return function(dv2) {
    return (
      dv1.byteLength === dv2.byteLength &&
      dv1.every(function(v, i) {
        return v === dv2[i];
      })
    );
  };
};
```

This is fine for where I need it.  But perhaps others would want `Eq` instances for typed arrays from time to time?

**Comment by dwhitney** [comment]
Just came across the need for the same thing. Any reason not to do this? I can make a PR

**Comment by garyb** [comment]
Seems like a reasonable thing to add :+1: (assuming we're going with a value-equality kinda thing like the example here).

**Comment by garyb** [comment]
See discussion in #13 - seems like this isn't such a great idea after all, since this is representing a mutable buffer.
