### ISSUE TITLE
New version tag for 0.12?

### ISSUE THREAD

**Issue by AlexMouton** [purescript-contrib/purescript-arraybuffer-types#12]
Hey!
Paf? Gary?
Can you take a minute to make a new release for 0.12?

Thanks
Alex

**Comment by thomashoneyman** [comment]
Hi Alex!

This library didn't require any updates for 0.12, so should work as-is. Are you not finding that the case?

**Comment by AlexMouton** [comment]
Oh sorry!
I saw 0.12 in the recent commits assumed it was necessary.
Having that many commits in the repo unreleased in bower was confusing.
I was on a bit of an 0.12 tear today.

**Comment by thomashoneyman** [comment]
No worries :) Thanks for taking the time to file an issue.
