### ISSUE TITLE
Publish v3.0.0 to Pursuit?

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-arraybuffer-types#22]
arraybuffer-types v3.0.0 is in package-sets,

https://github.com/purescript/package-sets/blob/58016acf777aeab4530abafc4f80207c398a7b2a/packages.json#L189

but Pursuit only has v2.0.0.

https://pursuit.purescript.org/packages/purescript-arraybuffer-types

Should we publish v3.0.0 to Pursuit? (I could do this if the answer is yes.)

**Comment by jamesdbrock** [comment]
(The Github label says bug but this is not a bug. I can't change the label.)

**Comment by thomashoneyman** [comment]
The answer is yes! We should publish anything possible to Pursuit if it's not up-to-date. And anyone can publish to Pursuit, not just the maintainer.

**Comment by jamesdbrock** [comment]
Publishing v3.0.0...

**Comment by jamesdbrock** [comment]
Okay, so I wanted to include your upgrade to `packages.dhall` 2c63e02e7ff091e88e147e98c97ec70e1462f586 in the new version, so I bumped to v3.0.1 and published that to Pursuit, but now I've discovered that I can't push to this repository, which I should have guessed.. So here's a PR for what I just published to Pursuit. #23

**Comment by thomashoneyman** [comment]
I've given you access to push to this repository. We usually leave things open for a review from another member of the Contributors organization before merging, at least for a few days. Someone usually gets a review in within a day or two. Thanks for taking care of this!

**Comment by jamesdbrock** [comment]
> I've given you access to push to this repository. We usually leave things open for a review from another member of the Contributors organization before merging, at least for a few days. Someone usually gets a review in within a day or two. Thanks for taking care of this!

Ok, that's what I'll do in the future, thanks for the advice.
